services:
  ucsdhiking_app:
    build:
      context: .
    container_name: ucsdhiking_app
    restart: unless-stopped
    depends_on:
      - ucsdhiking_db
      - ucsdhiking_redis
    env_file:
      - .env
    ports:
      - "5003:3000"
    networks:
      - network_default
  ucsdhiking_redis:
    image: redis:7
    container_name: ucsdhiking_redis
    restart: unless-stopped
    ports:
      - "5004:3001"
    volumes:
      - /root/services/ucsdhiking/redis:/data
    networks:
      - network_default
  ucsdhiking_db:
    image: postgres:16
    container_name: ucsdhiking_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ucsd_hiking_app_production
      POSTGRES_USER: ucsd_hiking_app
      POSTGRES_PASSWORD: ${UCSD_HIKING_APP_DATABASE_PASSWORD}
    networks:
      - network_default
    ports:
      - "5005:5432"
    volumes:
      - /root/services/ucsdhiking/db:/var/lib/postgresql/data

networks:
  network_default:
    external: true
