version: '3'
services:
  app:
    build:
      context: .
    container_name: app
    restart: unless-stopped
    ports:
      - "5001:3000"
    depends_on:
      - db
      - redis
    network_mode: service:db
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    network_mode: service:db
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ucsd_hiking_app_production
      POSTGRES_USER: ucsd_hiking_app
      POSTGRES_PASSWORD: ${UCSD_HIKING_APP_DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
  redis_data:
