version: '3'
services:
  app:
    image: ruby:3.3.0
    volumes:
      - ../..:/home/vscode:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    depends_on:
      - db
      - redis
    # Runs the service on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
    - SYS_PTRACE
    security_opt:
    - seccomp:unconfined
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis_data:/data
    network_mode: service:db
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: POSTGRES
      POSTGRES_USER: POSTGRES
      POSTGRES_PASSWORD: POSTGRES
      POSTGRES_HOST_AUTH_METHOD: trust # Unsafe! Only to be used in dev containers
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
  
volumes:
  postgres_data:
  redis_data:
